default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Play Store Internal Track"
  lane :beta do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(track: 'internal', apk: 'app/build/outputs/apk/release/app-release.apk')
  end

  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(track: 'production')
  end
end
