name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  # The name of the main module repository
  main_project_module: app


on:

  push:
    branches:
      - 'release/**'
      - 'main'
    tags:
      - '*'
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: List buildtools
        run: ls /usr/local/lib/android/sdk/build-tools/

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.8'
          bundler-cache: true

      - name: bundle install
        run: bundle install

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Run Tests Build
      - name: Run tests with Fastlane
        run: bundle exec fastlane test

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build -x test

      # Create APK Debug
      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleDebug

      # Create APK Release
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleRelease

      # Create Bundle AAB Release
      # Noted for main module build [main_project_module]:bundleRelease
      - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      # Upload Artifact Build
      # Noted For Output [main_project_module]/build/outputs/apk/debug/
      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - APK(s) debug generated
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      # Noted For Output [main_project_module]/build/outputs/apk/release/
      - name: Sign APK
        if: startsWith(github.ref, 'refs/tags/')
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: ${{ env.main_project_module }}/build/outputs/apk/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "36.1.0"

      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - APK(s) release generated
          path: ${{ steps.sign_app.outputs.signedReleaseFile || format('{0}/build/outputs/apk/release/', env.main_project_module) }}

      # Noted For Output [main_project_module]/build/outputs/bundle/release/
      - name: Sign AAB
        if: startsWith(github.ref, 'refs/tags/')
        uses: r0adkll/sign-android-release@v1
        id: sign_aab
        with:
          releaseDirectory: ${{ env.main_project_module }}/build/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload AAB (App Bundle) Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - App bundle(s) AAB release generated
          path: ${{ steps.sign_aab.outputs.signedReleaseFile || format('{0}/build/outputs/bundle/release/', env.main_project_module) }}

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.sign_app.outputs.signedReleaseFile }}
            ${{ steps.sign_aab.outputs.signedReleaseFile }}
          generate_release_notes: true
